### ISSUE TITLE
Nitrous Error

### ISSUE THREAD

**Issue by jeremyfeld** [learn-co-curriculum/ios-environment-setup-summary#10]
Hi - I am trying to set up the Learn OSX app.  I keep getting an error message: "Nitrous container creation failed. Please try again and contact support if this problem persists."  

I was also having issues with Nitrous while going through the Intro to Ruby track.  That had been resolved but as of now I can't even open labs in that track through learn (or use 'learn open' in Nitrous).

Thanks for your help.

**Comment by markedwardmurray** [comment]
Jeremy, the ios curriculum is not supported by Nitrous since Xcode, which is required for iOS development, can only be installed on a Mac running OS X (Nitrous is a Linux environment). If you would like help switching back to the Intro to Ruby track, please Ask A Question in Learn. Unfortunately I have no familiarity with Nitrous setup and containers so I'm unable to troubleshoot your problem opening the labs.

**Comment by jeremyfeld** [comment]
Well then the issue is I can't follow the link within Learn to set up my
iOS dev environment.  The link that says it is for the Learn OSX app only
brings me to a page where I can get set up on Nitrous.  Is there another
place I can go to set up my environment?  Dev environment is set to local
in my Learn profile.
